<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Brands</name>
   <tag></tag>
   <elementGuidId>8cd9cb37-bc16-475b-ac81-870a5fbbe108</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;ga('send', 'event', 'Main Nav', 'Deals', 'Deals');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.brand-a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>297d1005-1dca-433e-a7d6-3229826a5fc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>brand-a</value>
      <webElementGuid>61fae69d-509a-42c2-8ae2-2c74c2f217e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/wine-brands</value>
      <webElementGuid>6e201aab-f300-44e9-97ce-d06ef9812570</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ga('send', 'event', 'Main Nav', 'Deals', 'Deals');</value>
      <webElementGuid>209f339d-eb30-418b-b2e4-4d36ed4f7685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>af8cc452-ac1b-4ace-8789-0c45ef5dbb3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Brands</value>
      <webElementGuid>10a88cd9-ff4d-4443-bde6-518bb20d8935</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky&quot;)/div[@class=&quot;navbar-collapse&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;menu-large brands&quot;]/a[@class=&quot;brand-a&quot;]</value>
      <webElementGuid>0882d422-bb66-41b4-8dc3-54c7401659c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;ga('send', 'event', 'Main Nav', 'Deals', 'Deals');&quot;]</value>
      <webElementGuid>7e4f211a-10c3-4be3-bb01-1ec0a27d3386</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky']/div/ul/li[3]/a</value>
      <webElementGuid>645c8a16-6706-4972-8c60-0f6c09aa207c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Brands')]</value>
      <webElementGuid>071ff642-bad6-4b48-aa69-e025f0c66965</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Deals'])[1]/following::a[1]</value>
      <webElementGuid>c1d33a8b-9fcf-46fd-947f-e71ae1208340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All Mixed Wines'])[1]/following::a[2]</value>
      <webElementGuid>e07e277a-b4cb-4b4f-a9f5-b36b87af2f48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Brands'])[2]/preceding::a[1]</value>
      <webElementGuid>7c3945b1-da7f-4ca9-88f8-0ae6a21142e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='De Bortoli Wines'])[1]/preceding::a[2]</value>
      <webElementGuid>57aa50c0-15c2-49e3-9e80-f44d46c2edf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Brands']/parent::*</value>
      <webElementGuid>f50fe0a9-df93-4c20-a785-7d08dd8503bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/wine-brands')]</value>
      <webElementGuid>e9e0c32e-b8d8-4c43-8d1e-6a7b26f35955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[3]/a</value>
      <webElementGuid>7a7e3560-7273-4cfb-913c-c3376d0905ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/wine-brands' and (text() = 'Brands' or . = 'Brands')]</value>
      <webElementGuid>9eda97fc-0be5-4cd9-a119-284d6b2dce68</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
