<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Buy Wine</name>
   <tag></tag>
   <elementGuidId>12e987ad-d670-4ac7-b154-9bcbe5603d2f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='sticky']/div/ul/li/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.dropdown-toggle.nav-icon.drop1.buy_wine</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>e4177220-0840-46ad-bfc2-ba164259d3a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/featuredproduct</value>
      <webElementGuid>4e67d7aa-200e-4e62-bbff-deedc8ad0330</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle nav-icon drop1 buy_wine</value>
      <webElementGuid>cde0b2c9-a418-4273-b481-bd4e25fe13ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>7d9523a8-f91f-438a-8abc-5cc1448cd414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Buy Wine</value>
      <webElementGuid>2a830277-12f1-480c-8986-c59d2d7425da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky&quot;)/div[@class=&quot;navbar-collapse&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown sub-menu menu-large&quot;]/a[@class=&quot;dropdown-toggle nav-icon drop1 buy_wine&quot;]</value>
      <webElementGuid>f10704e3-7493-494b-ba11-3303f3cd16c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky']/div/ul/li/a</value>
      <webElementGuid>1f4bbf6e-fdd5-4bf2-85bf-5716045b1959</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Buy Wine')]</value>
      <webElementGuid>a7a847cc-f0de-470b-966b-7288f80c10e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Nav'])[1]/following::a[2]</value>
      <webElementGuid>2bbacfd3-7857-447b-9a5f-0b45429f711f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='FAQ'])[1]/following::a[2]</value>
      <webElementGuid>571e1ac0-fe16-4acb-a046-7afab062224b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Red wine'])[1]/preceding::a[1]</value>
      <webElementGuid>447a8b09-9064-430f-9ef6-c093d8bec783</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shiraz'])[1]/preceding::a[2]</value>
      <webElementGuid>78ffd787-e8f6-40d5-a9ef-de9b2f555b0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Buy Wine']/parent::*</value>
      <webElementGuid>fe5e9c21-c62d-4284-85dc-0b40f4b8af02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/featuredproduct')]</value>
      <webElementGuid>4838a075-2e7b-4201-9049-705d3598695d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/a</value>
      <webElementGuid>a64a54b8-5160-42a0-a143-c9eaccce0517</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/featuredproduct' and (text() = 'Buy Wine' or . = 'Buy Wine')]</value>
      <webElementGuid>ac8637bf-934b-4e62-80c8-a04eb54980ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
