<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Merlot</name>
   <tag></tag>
   <elementGuidId>57d3d1c7-1fa6-4acc-a0a0-f2753262c1a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;ga('send', 'event', 'Main Nav', 'Red Wine', 'Merlot-R');&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>368ce482-1e4d-41e6-8ada-65197dcfc00e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>level1</value>
      <webElementGuid>6ea9c13a-c114-47c6-be80-5bbb494b38b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ga('send', 'event', 'Main Nav', 'Red Wine', 'Merlot-R');</value>
      <webElementGuid>69d5c046-996a-4e68-b51d-1e7d00e52c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/red-wine/merlot</value>
      <webElementGuid>e58ba91f-df73-4d0b-a278-921b03a27b12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Merlot</value>
      <webElementGuid>61d7e35b-ba54-45c1-b11e-7e799caa96e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;sticky&quot;)/div[@class=&quot;navbar-collapse&quot;]/ul[@class=&quot;nav navbar-nav&quot;]/li[@class=&quot;dropdown sub-menu menu-large&quot;]/ul[@class=&quot;dropdown-menu megamenu row red-wine&quot;]/li[@class=&quot;col-sm-3 red_wine&quot;]/ul[1]/div[@class=&quot;subdivgrape wine-1&quot;]/li[4]/a[@class=&quot;level1&quot;]</value>
      <webElementGuid>3cc3b148-4e4d-47ba-b9b3-ba7b8cddad36</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;ga('send', 'event', 'Main Nav', 'Red Wine', 'Merlot-R');&quot;]</value>
      <webElementGuid>70bea420-4844-41df-885c-119f5c74a5c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='sticky']/div/ul/li/ul/li/ul/div/li[4]/a</value>
      <webElementGuid>5cd7f3b2-c45b-408c-96c0-885e8b9814d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'Merlot')])[2]</value>
      <webElementGuid>0460ae2a-dc0f-4d44-8a63-0eddec81a9cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabernet Merlot'])[1]/following::a[1]</value>
      <webElementGuid>567b6961-9010-450d-a857-df0642c6c541</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cabernet Sauvignon'])[1]/following::a[2]</value>
      <webElementGuid>709f67ae-bd8c-4fc0-872b-1d587eaa9441</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pinot Noir'])[1]/preceding::a[1]</value>
      <webElementGuid>353e4ca2-389c-452d-b1aa-bcdba1cd8b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grenache'])[1]/preceding::a[2]</value>
      <webElementGuid>2e9f7894-bb53-43e8-adc1-a0273cb593ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Merlot']/parent::*</value>
      <webElementGuid>ba7032d2-f263-468d-a2c2-0661fb8c1477</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/red-wine/merlot')]</value>
      <webElementGuid>54743414-69a3-4e5b-9ad8-0a1cb2c31f4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/li[4]/a</value>
      <webElementGuid>16fa1d39-cf59-4bae-b268-9ccbf0fc938a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/red-wine/merlot' and (text() = 'Merlot' or . = 'Merlot')]</value>
      <webElementGuid>d29e7b2f-7d0d-45dc-9e79-614ecd682727</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
