<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Card CVN_paymentcc_cid</name>
   <tag></tag>
   <elementGuidId>0d067ae4-0fab-49c5-9025-59d1dbdfa781</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ewayrapid_cc_cid']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ewayrapid_cc_cid</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ba5d3ef-fb6c-49a1-a99d-fa191a4d9eea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>0956ea08-4a61-4f9b-89f6-0344ea292170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>d0f080b8-d180-4172-bc8c-0a6b3184263b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text cvv</value>
      <webElementGuid>31ccbaa6-f841-4ee2-9de8-21a57b637c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>payment[cc_cid]</value>
      <webElementGuid>764feca8-d87e-4323-8522-ce69c8f1c930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>attr: {id: getCode() + '_cc_cid',
                        title: $t('Card Verification Number'),
                        'data-container': getCode() + '-cc-cvv',
                        'data-validate': JSON.stringify({'required-number':true, 'validate-card-cvv':'#' + getCode() + '_cc_type'})},
                        enable: isActive($parents),
                        value: creditCardVerificationNumber</value>
      <webElementGuid>4161c2c4-c3a5-470e-811f-cf01c69e9b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ewayrapid_cc_cid</value>
      <webElementGuid>e5bd3476-3fa6-40f3-8af6-055c67e63d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Card Verification Number</value>
      <webElementGuid>0cedca18-b04a-46d6-bcd9-f84373aae3bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-container</name>
      <type>Main</type>
      <value>ewayrapid-cc-cvv</value>
      <webElementGuid>a9bdc8de-f507-45e0-829a-4f03cdd4ac84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{&quot;required-number&quot;:true,&quot;validate-card-cvv&quot;:&quot;#ewayrapid_cc_type&quot;}</value>
      <webElementGuid>a9963a09-27ec-4b7d-93c6-fb6c90dbc477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ewayrapid_cc_cid&quot;)</value>
      <webElementGuid>c5648b9c-6cdb-4650-b7c1-c0bfd7c3bf47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ewayrapid_cc_cid']</value>
      <webElementGuid>26ec048a-4000-48c9-a36d-ee7c9d2181da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ewayrapid_cc_type_cvv_div']/div/input</value>
      <webElementGuid>ad838a1b-a38e-447b-bc1a-5c568a83dcee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/form/fieldset/div[5]/div/input</value>
      <webElementGuid>3a5261c6-86cc-4fb6-9d13-82175f3fa8e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'number' and @name = 'payment[cc_cid]' and @id = 'ewayrapid_cc_cid' and @title = 'Card Verification Number']</value>
      <webElementGuid>b8095afd-be82-4f78-ae66-a6583baab128</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
